/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 *  These tests are the specification. If a test fails, the bug is
 *  in tasks.ts, not here. (If you are convinced otherwise, open an
 *  issue - that is a legitimate QA skill too.)
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import {
  sanitizeTestName,
  parseDurationMs,
  severityRank,
  isAtLeast,
  parseEnvLine,
  RETRY_POLICY,
} from './tasks';

describe('1.1 sanitizeTestName', () => {
  it('lowercases and joins words with a single dash', () => {
    expect(sanitizeTestName('Login  works!')).toBe('login-works');
  });

  it('trims surrounding whitespace', () => {
    expect(sanitizeTestName('   Checkout flow   ')).toBe('checkout-flow');
  });

  it('collapses any run of non-alphanumerics into one dash', () => {
    expect(sanitizeTestName('API / v2 / health')).toBe('api-v2-health');
    expect(sanitizeTestName("User can't log in")).toBe('user-can-t-log-in');
  });

  it('keeps digits', () => {
    expect(sanitizeTestName('TC-1024 retries 3 times')).toBe('tc-1024-retries-3-times');
  });

  it('returns an empty string when there is nothing to keep', () => {
    expect(sanitizeTestName('!!!')).toBe('');
    expect(sanitizeTestName('')).toBe('');
  });
});

describe('1.2 parseDurationMs', () => {
  it('reads milliseconds', () => {
    expect(parseDurationMs('1500ms')).toBe(1500);
    expect(parseDurationMs('0ms')).toBe(0);
  });

  it('reads whole seconds', () => {
    expect(parseDurationMs('2s')).toBe(2000);
  });

  it('reads fractional seconds', () => {
    expect(parseDurationMs('1.5s')).toBe(1500);
    expect(parseDurationMs('0.25s')).toBe(250);
  });

  it('reads fractional milliseconds', () => {
    expect(parseDurationMs('12.5ms')).toBe(12.5);
  });

  it('treats a bare number as milliseconds', () => {
    expect(parseDurationMs('90')).toBe(90);
  });

  it('is whitespace and case tolerant', () => {
    expect(parseDurationMs('  2S ')).toBe(2000);
  });

  it('returns NaN for nonsense', () => {
    expect(parseDurationMs('soon')).toBeNaN();
    expect(parseDurationMs('')).toBeNaN();
  });
});

describe('1.3 Severity', () => {
  it('ranks blocker as the worst', () => {
    expect(severityRank('blocker')).toBe(0);
    expect(severityRank('trivial')).toBe(4);
  });

  it('ranks every level in order', () => {
    const order = ['blocker', 'critical', 'major', 'minor', 'trivial'] as const;
    const ranks = order.map((s) => severityRank(s));
    expect(ranks).toEqual([0, 1, 2, 3, 4]);
  });

  it('compares severities', () => {
    expect(isAtLeast('major', 'minor')).toBe(true);
    expect(isAtLeast('minor', 'major')).toBe(false);
    expect(isAtLeast('critical', 'critical')).toBe(true);
    expect(isAtLeast('blocker', 'trivial')).toBe(true);
  });

  it('rejects values outside the union at compile time', () => {
    // @ts-expect-error "bananas" is not a Severity.
    // While `Severity` is still `string` this line has no error, and an
    // unused @ts-expect-error is itself a compile error. That is the point.
    severityRank('bananas');
    expect(true).toBe(true);
  });
});

describe('1.4 parseEnvLine', () => {
  it('splits a simple line', () => {
    expect(parseEnvLine('BASE_URL=https://staging.example.com')).toEqual([
      'BASE_URL',
      'https://staging.example.com',
    ]);
  });

  it('only splits on the first equals sign', () => {
    expect(parseEnvLine('TOKEN=abc=def=ghi')).toEqual(['TOKEN', 'abc=def=ghi']);
  });

  it('trims the key but preserves the value verbatim', () => {
    expect(parseEnvLine('  RETRIES =  3 ')).toEqual(['RETRIES', '  3 ']);
  });

  it('allows an empty value', () => {
    expect(parseEnvLine('PROXY=')).toEqual(['PROXY', '']);
  });

  it('returns null when there is no equals sign', () => {
    expect(parseEnvLine('# a comment')).toBeNull();
  });

  it('returns a two element tuple, not an array of unknown length', () => {
    const parsed = parseEnvLine('A=1');
    expect(parsed).not.toBeNull();
    expect(parsed).toHaveLength(2);
  });
});

describe('1.5 RETRY_POLICY', () => {
  it('still holds the same values after you freeze the type', () => {
    expect(RETRY_POLICY.attempts).toBe(3);
    expect(RETRY_POLICY.mode).toBe('exponential');
    expect(RETRY_POLICY.jitter).toBe(true);
  });

  it('is graded by the type checker - run `npm run typecheck`', () => {
    // There is nothing to assert at runtime. `as const` leaves no trace in
    // the emitted JavaScript. This test exists so the task shows up in your
    // progress report; the real grader is tsc.
    expect(Object.keys(RETRY_POLICY).sort()).toEqual(['attempts', 'jitter', 'mode']);
  });
});
