/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import type { Expect, Equal } from '../_lib/type-assert';
import {
  first,
  last,
  compact,
  pluck,
  indexBy,
  groupBy,
  TestDataRegistry,
  ok,
  isOk,
  expectStatus,
} from './tasks';

interface User {
  id: number;
  name: string;
  active: boolean;
}

const users: User[] = [
  { id: 1, name: 'ann', active: true },
  { id: 2, name: 'bo', active: false },
  { id: 3, name: 'cy', active: true },
];

describe('5.1 first / last / compact', () => {
  it('first returns the first element', () => {
    expect(first([1, 2, 3])).toBe(1);
  });

  it('first returns undefined for an empty array', () => {
    expect(first([])).toBeUndefined();
  });

  it('last returns the last element', () => {
    expect(last(['a', 'b'])).toBe('b');
    expect(last([])).toBeUndefined();
  });

  it('compact drops null and undefined', () => {
    expect(compact([1, null, 2, undefined, 3])).toEqual([1, 2, 3]);
  });

  it('compact keeps other falsy values', () => {
    expect(compact([0, '', false, null])).toEqual([0, '', false]);
  });

  it('compact narrows the element type', () => {
    const values = compact<number>([1, null, 2]);
    type _check = Expect<Equal<typeof values, number[]>>;
    expect(values).toEqual([1, 2]);
  });
});

describe('5.2 pluck / indexBy', () => {
  it('plucks a property off every item', () => {
    expect(pluck(users, 'name')).toEqual(['ann', 'bo', 'cy']);
    expect(pluck(users, 'id')).toEqual([1, 2, 3]);
  });

  it('plucks with the right element type', () => {
    const names = pluck(users, 'name');
    type _check = Expect<Equal<typeof names, string[]>>;
    const ids = pluck(users, 'id');
    type _check2 = Expect<Equal<typeof ids, number[]>>;
    expect(names).toHaveLength(3);
    expect(ids).toHaveLength(3);
  });

  it('rejects a key that does not exist', () => {
    // The type error (graded by `npm run typecheck`) is the point. The
    // runtime check is secondary: `item['nmae']` really is `undefined` for
    // every item, since nothing in `User` is spelled that way.
    // @ts-expect-error 'nmae' is not a key of User.
    expect(pluck(users, 'nmae')).toEqual([undefined, undefined, undefined]);
  });

  it('indexes by a key', () => {
    const byId = indexBy(users, 'id');
    expect(byId.get(2)).toEqual({ id: 2, name: 'bo', active: false });
    expect(byId.size).toBe(3);
  });

  it('indexBy keeps the last item on a collision', () => {
    const byActive = indexBy(users, 'active');
    expect(byActive.get(true)).toEqual({ id: 3, name: 'cy', active: true });
    expect(byActive.size).toBe(2);
  });

  it('indexBy types both the key and the value', () => {
    const byId = indexBy(users, 'id');
    type _check = Expect<Equal<typeof byId, Map<number, User>>>;
    expect(byId).toBeInstanceOf(Map);
  });
});

describe('5.3 groupBy', () => {
  it('collects every item into its bucket', () => {
    expect(groupBy(['ant', 'bee', 'ape'], (w) => w[0]!)).toEqual({
      a: ['ant', 'ape'],
      b: ['bee'],
    });
  });

  it('preserves input order inside a bucket', () => {
    const grouped = groupBy(users, (u) => String(u.active));
    expect(grouped['true']).toEqual([users[0], users[2]]);
    expect(grouped['false']).toEqual([users[1]]);
  });

  it('handles an empty input', () => {
    expect(groupBy([], () => 'x')).toEqual({});
  });

  it('does not lose items when every key is the same', () => {
    expect(groupBy([1, 2, 3], () => 'all')).toEqual({ all: [1, 2, 3] });
  });
});

describe('5.4 TestDataRegistry', () => {
  it('creates registered objects', () => {
    const registry = new TestDataRegistry<User>();
    registry.register('admin', () => ({ id: 1, name: 'admin', active: true }));
    expect(registry.create('admin')).toEqual({ id: 1, name: 'admin', active: true });
  });

  it('calls the factory every time, so instances are independent', () => {
    const registry = new TestDataRegistry<User>();
    registry.register('admin', () => ({ id: 1, name: 'admin', active: true }));
    const a = registry.create('admin');
    const b = registry.create('admin');
    expect(a).toEqual(b);
    expect(a).not.toBe(b);
  });

  it('reports what it knows', () => {
    const registry = new TestDataRegistry<User>();
    registry.register('admin', () => ({ id: 1, name: 'admin', active: true }));
    registry.register('guest', () => ({ id: 2, name: 'guest', active: false }));
    expect(registry.has('admin')).toBe(true);
    expect(registry.has('nope')).toBe(false);
    expect(registry.names()).toEqual(['admin', 'guest']);
  });

  it('overwrites a re-registered name', () => {
    const registry = new TestDataRegistry<User>();
    registry.register('admin', () => ({ id: 1, name: 'v1', active: true }));
    registry.register('admin', () => ({ id: 1, name: 'v2', active: true }));
    expect(registry.create('admin').name).toBe('v2');
    expect(registry.names()).toEqual(['admin']);
  });

  it('throws a clear error for an unknown name', () => {
    const registry = new TestDataRegistry<User>();
    expect(() => registry.create('nope')).toThrow('unknown factory: nope');
  });

  it('returns values typed as T', () => {
    const registry = new TestDataRegistry<User>();
    registry.register('admin', () => ({ id: 1, name: 'admin', active: true }));
    const user = registry.create('admin');
    type _check = Expect<Equal<typeof user, User>>;
    expect(user.name).toBe('admin');
  });
});

describe('5.5 ApiResponse', () => {
  it('ok builds a 200 response', () => {
    expect(ok({ id: 7 })).toEqual({ status: 200, body: { id: 7 }, headers: {} });
  });

  it('isOk covers the whole 2xx range', () => {
    expect(isOk({ status: 200, body: null, headers: {} })).toBe(true);
    expect(isOk({ status: 204, body: null, headers: {} })).toBe(true);
    expect(isOk({ status: 299, body: null, headers: {} })).toBe(true);
    expect(isOk({ status: 300, body: null, headers: {} })).toBe(false);
    expect(isOk({ status: 404, body: null, headers: {} })).toBe(false);
    expect(isOk({ status: 199, body: null, headers: {} })).toBe(false);
  });

  it('expectStatus returns the body on a match', () => {
    expect(expectStatus(ok({ id: 7 }), 200)).toEqual({ id: 7 });
  });

  it('expectStatus throws with both numbers in the message', () => {
    const response = { status: 500, body: null, headers: {} };
    expect(() => expectStatus(response, 200)).toThrow('expected status 200, got 500');
  });

  it('expectStatus preserves the body type', () => {
    const body = expectStatus(ok({ id: 7, name: 'x' }), 200);
    type _check = Expect<Equal<typeof body, { id: number; name: string }>>;
    expect(body.name).toBe('x');
  });
});
