/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import { FakeDriver } from '../_lib/fake-driver';
import {
  BasePage,
  LoginPage,
  AdminLoginPage,
  RetryCounter,
  countRetries,
  StepRecorder,
  MemoryLogger,
  SuiteRunner,
  type Clock,
} from './tasks';

const BASE = 'https://staging.example.com';

describe('9.1 BasePage / LoginPage', () => {
  it('builds a url from base and path', () => {
    const page = new LoginPage(new FakeDriver(), BASE);
    expect(page.url).toBe('https://staging.example.com/login');
  });

  it('collapses a doubled slash', () => {
    const page = new LoginPage(new FakeDriver(), `${BASE}/`);
    expect(page.url).toBe('https://staging.example.com/login');
  });

  it('open navigates and returns itself for chaining', () => {
    const driver = new FakeDriver();
    const page = new LoginPage(driver, BASE);
    expect(page.open()).toBe(page);
    expect(driver.log).toEqual(['goto https://staging.example.com/login']);
  });

  it('isLoaded reflects the page', () => {
    expect(new LoginPage(new FakeDriver(), BASE).isLoaded()).toBe(false);
    expect(
      new LoginPage(new FakeDriver({ '#login-form': '' }), BASE).isLoaded(),
    ).toBe(true);
  });

  it('login fills the form and submits', () => {
    const driver = new FakeDriver({ '#login-form': '' });
    const page = new LoginPage(driver, BASE);
    expect(page.open().login('nivis', 'hunter2')).toBe(page);
    expect(driver.log).toEqual([
      'goto https://staging.example.com/login',
      'type #username=nivis',
      'type #password=hunter2',
      'click #submit',
    ]);
  });

  it('reads the error message, or null', () => {
    expect(new LoginPage(new FakeDriver(), BASE).errorMessage()).toBeNull();
    const driver = new FakeDriver({ '.error': 'Bad credentials' });
    expect(new LoginPage(driver, BASE).errorMessage()).toBe('Bad credentials');
  });

  it('BasePage cannot be constructed directly', () => {
    // @ts-expect-error BasePage is abstract with a protected constructor.
    expect(() => new BasePage(new FakeDriver(), BASE)).toBeDefined();
  });

  it('does not expose the driver to the outside world', () => {
    const page = new LoginPage(new FakeDriver(), BASE);
    // @ts-expect-error `driver` is protected.
    expect(page.driver).toBeDefined();
  });
});

describe('9.2 AdminLoginPage', () => {
  it('has its own path', () => {
    const page = new AdminLoginPage(new FakeDriver(), BASE);
    expect(page.url).toBe('https://staging.example.com/admin/login');
  });

  it('needs both the form and the badge', () => {
    expect(new AdminLoginPage(new FakeDriver({ '#login-form': '' }), BASE).isLoaded()).toBe(
      false,
    );
    expect(new AdminLoginPage(new FakeDriver({ '#admin-badge': '' }), BASE).isLoaded()).toBe(
      false,
    );
    expect(
      new AdminLoginPage(
        new FakeDriver({ '#login-form': '', '#admin-badge': '' }),
        BASE,
      ).isLoaded(),
    ).toBe(true);
  });

  it('inherits login, and chaining still returns the subclass', () => {
    const driver = new FakeDriver({ '#login-form': '', '#admin-badge': '' });
    const page = new AdminLoginPage(driver, BASE);
    const chained: AdminLoginPage = page.open().login('root', 'toor');
    expect(chained).toBe(page);
    expect(chained.isLoaded()).toBe(true);
  });

  it('is still a LoginPage', () => {
    const page = new AdminLoginPage(new FakeDriver(), BASE);
    expect(page).toBeInstanceOf(LoginPage);
    expect(page).toBeInstanceOf(BasePage);
  });
});

describe('9.3 countRetries', () => {
  it('counts', () => {
    expect(countRetries(new RetryCounter(), 3)).toBe(3);
  });

  it('counts zero times', () => {
    expect(countRetries(new RetryCounter(), 0)).toBe(0);
  });

  it('keeps counting on the same instance', () => {
    const counter = new RetryCounter();
    countRetries(counter, 2);
    expect(countRetries(counter, 2)).toBe(4);
  });
});

describe('9.4 StepRecorder', () => {
  it('records steps fluently', () => {
    const recorder = StepRecorder.start('checkout');
    expect(recorder.step('open cart').step('pay')).toBe(recorder);
    expect(recorder.steps).toEqual(['open cart', 'pay']);
  });

  it('knows its name', () => {
    expect(StepRecorder.start('checkout').name).toBe('checkout');
  });

  it('hands out a copy, not the real array', () => {
    const recorder = StepRecorder.start('x').step('a');
    const stolen = recorder.steps as string[];
    stolen.push('injected');
    expect(recorder.steps).toEqual(['a']);
  });

  it('renders a readable trail', () => {
    expect(String(StepRecorder.start('checkout').step('a').step('b'))).toBe('checkout: a > b');
  });

  it('renders an empty recorder honestly', () => {
    expect(String(StepRecorder.start('checkout'))).toBe('checkout: (no steps)');
  });

  it('cannot be constructed with new', () => {
    // @ts-expect-error the constructor is private; use StepRecorder.start.
    expect(() => new StepRecorder('x')).toBeDefined();
  });
});

describe('9.5 SuiteRunner', () => {
  const fakeClock = (...times: number[]): Clock => {
    let index = 0;
    return {
      now: () => times[Math.min(index++, times.length - 1)]!,
    };
  };

  it('logs a passing run with its duration', () => {
    const logger = new MemoryLogger();
    const runner = new SuiteRunner(logger, fakeClock(1000, 1250));
    expect(runner.run('smoke', () => undefined)).toBe(250);
    expect(logger.lines).toEqual(['start smoke', 'pass smoke (250ms)']);
  });

  it('logs a failing run and re-throws the original error', () => {
    const logger = new MemoryLogger();
    const runner = new SuiteRunner(logger, fakeClock(0, 42));
    const boom = new Error('assertion failed');
    expect(() =>
      runner.run('checkout', () => {
        throw boom;
      }),
    ).toThrow(boom);
    expect(logger.lines).toEqual(['start checkout', 'fail checkout (42ms): assertion failed']);
  });

  it('MemoryLogger collects lines in order', () => {
    const logger = new MemoryLogger();
    logger.log('a');
    logger.log('b');
    expect(logger.lines).toEqual(['a', 'b']);
  });

  it('works with any Logger, not just the one we shipped', () => {
    const captured: string[] = [];
    const runner = new SuiteRunner({ log: (m) => captured.push(m) }, fakeClock(0, 5));
    runner.run('x', () => undefined);
    expect(captured).toEqual(['start x', 'pass x (5ms)']);
  });
});
