/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import {
  buildUrl,
  joinPaths,
  resolveRunOptions,
  range,
  required,
  maxLength,
  matches,
  runValidators,
} from './tasks';

describe('2.1 buildUrl', () => {
  it('joins base and path with exactly one slash', () => {
    expect(buildUrl('https://api.example.com', '/v2/health')).toBe(
      'https://api.example.com/v2/health',
    );
    expect(buildUrl('https://api.example.com/', 'v2/health')).toBe(
      'https://api.example.com/v2/health',
    );
    expect(buildUrl('https://api.example.com/', '/v2/health')).toBe(
      'https://api.example.com/v2/health',
    );
  });

  it('drops the trailing slash when the path is empty', () => {
    expect(buildUrl('https://api.example.com/', '')).toBe('https://api.example.com');
  });

  it('omits the question mark when there is no query', () => {
    expect(buildUrl('https://api.example.com', 'health', {})).toBe(
      'https://api.example.com/health',
    );
  });

  it('sorts query keys so output is deterministic', () => {
    expect(buildUrl('https://x.test', 'search', { z: 1, a: 2, m: 3 })).toBe(
      'https://x.test/search?a=2&m=3&z=1',
    );
  });

  it('encodes values and stringifies booleans', () => {
    expect(buildUrl('https://x.test', 's', { q: 'a b&c', exact: true })).toBe(
      'https://x.test/s?exact=true&q=a%20b%26c',
    );
  });
});

describe('2.2 joinPaths', () => {
  it('joins segments', () => {
    expect(joinPaths('api', 'v2', 'health')).toBe('api/v2/health');
  });

  it('collapses slashes the caller already added', () => {
    expect(joinPaths('/api/', '/v2/', 'health')).toBe('/api/v2/health');
  });

  it('skips empty segments', () => {
    expect(joinPaths('api', '', 'health')).toBe('api/health');
  });

  it('handles no arguments at all', () => {
    expect(joinPaths()).toBe('');
  });

  it('preserves a leading slash', () => {
    expect(joinPaths('/', 'a')).toBe('/a');
  });
});

describe('2.3 resolveRunOptions', () => {
  it('fills in defaults when nothing is passed', () => {
    expect(resolveRunOptions()).toEqual({
      baseUrl: 'https://staging.example.com',
      retries: 2,
      timeoutMs: 30_000,
      headless: true,
    });
  });

  it('respects an explicit zero', () => {
    expect(resolveRunOptions({ retries: 0 }).retries).toBe(0);
    expect(resolveRunOptions({ timeoutMs: 0 }).timeoutMs).toBe(0);
  });

  it('respects an explicit false', () => {
    expect(resolveRunOptions({ headless: false }).headless).toBe(false);
  });

  it('respects an explicit empty string', () => {
    expect(resolveRunOptions({ baseUrl: '' }).baseUrl).toBe('');
  });

  it('still falls back when a key is genuinely absent', () => {
    expect(resolveRunOptions({ retries: 5 }).timeoutMs).toBe(30_000);
  });

  it('still falls back for an explicit undefined', () => {
    expect(resolveRunOptions({ retries: undefined }).retries).toBe(2);
  });
});

describe('2.4 range', () => {
  it('counts from zero with one argument', () => {
    expect(range(3)).toEqual([0, 1, 2]);
    expect(range(0)).toEqual([]);
  });

  it('counts between two bounds, end exclusive', () => {
    expect(range(2, 5)).toEqual([2, 3, 4]);
    expect(range(5, 5)).toEqual([]);
  });

  it('honours a step', () => {
    expect(range(0, 10, 3)).toEqual([0, 3, 6, 9]);
  });

  it('counts down with a negative step', () => {
    expect(range(5, 0, -1)).toEqual([5, 4, 3, 2, 1]);
  });

  it('refuses a zero step instead of looping forever', () => {
    expect(() => range(0, 10, 0)).toThrow(RangeError);
  });

  it('rejects nonsense call shapes at compile time', () => {
    // Graded by `npm run typecheck`, not by this line - neither call below
    // is allowed to exist in the first place, so there is nothing to run.
    // @ts-expect-error range needs at least one argument
    const tooFew = () => range();
    // @ts-expect-error range takes at most three arguments
    const tooMany = () => range(1, 2, 3, 4);
    void tooFew;
    void tooMany;
    expect(true).toBe(true);
  });
});

describe('2.5 validators', () => {
  it('required rejects blank input', () => {
    const v = required('username');
    expect(v('')).toBe('username is required');
    expect(v('   ')).toBe('username is required');
    expect(v('nivis')).toBeNull();
  });

  it('maxLength rejects long input', () => {
    const v = maxLength('title', 5);
    expect(v('abcdef')).toBe('title must be at most 5 characters');
    expect(v('abcde')).toBeNull();
  });

  it('matches uses the supplied message', () => {
    const v = matches('email', /^[^@]+@[^@]+$/, 'email is malformed');
    expect(v('nope')).toBe('email is malformed');
    expect(v('a@b')).toBeNull();
  });

  it('runValidators collects every failure in order', () => {
    const errors = runValidators('', [
      required('name'),
      maxLength('name', 3),
      matches('name', /^[a-z]+$/, 'name must be lowercase letters'),
    ]);
    expect(errors).toEqual(['name is required', 'name must be lowercase letters']);
  });

  it('runValidators returns an empty array when everything passes', () => {
    expect(runValidators('ok', [required('name'), maxLength('name', 10)])).toEqual([]);
  });

  it('runValidators with no validators is vacuously happy', () => {
    expect(runValidators('anything', [])).toEqual([]);
  });
});
