/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import {
  parseJson,
  asRecord,
  getString,
  readConfig,
  configFor,
  ownerEmail,
  isTestRun,
  parseTestRuns,
} from './tasks';

describe('11.1 unknown at the boundary', () => {
  it('parses valid JSON', () => {
    expect(parseJson('{"a":1}')).toEqual({ a: 1 });
    expect(parseJson('[1,2]')).toEqual([1, 2]);
    expect(parseJson('"text"')).toBe('text');
  });

  it('returns null for invalid JSON instead of throwing', () => {
    expect(() => parseJson('{oops')).not.toThrow();
    expect(parseJson('{oops')).toBeNull();
    expect(parseJson('')).toBeNull();
  });

  it('recognises plain objects only', () => {
    expect(asRecord({ a: 1 })).toEqual({ a: 1 });
    expect(asRecord([1, 2])).toBeNull();
    expect(asRecord(null)).toBeNull();
    expect(asRecord('text')).toBeNull();
    expect(asRecord(42)).toBeNull();
  });

  it('reads a string property safely', () => {
    expect(getString({ name: 'smoke' }, 'name')).toBe('smoke');
    expect(getString({ name: 42 }, 'name')).toBeNull();
    expect(getString({}, 'name')).toBeNull();
    expect(getString(null, 'name')).toBeNull();
    expect(getString('not an object', 'name')).toBeNull();
  });

  it('treats an empty string as a real value', () => {
    expect(getString({ name: '' }, 'name')).toBe('');
  });
});

describe('11.2 readConfig', () => {
  const valid = JSON.stringify({
    baseUrl: 'https://x.test',
    retries: 2,
    headless: false,
  });

  it('accepts a valid config', () => {
    expect(readConfig(valid)).toEqual({
      baseUrl: 'https://x.test',
      retries: 2,
      headless: false,
    });
  });

  it('rejects an empty object naming the first missing field', () => {
    expect(() => readConfig('{}')).toThrow('invalid config: baseUrl');
  });

  it('checks fields in declaration order', () => {
    expect(() => readConfig(JSON.stringify({ baseUrl: 'x' }))).toThrow(
      'invalid config: retries',
    );
    expect(() => readConfig(JSON.stringify({ baseUrl: 'x', retries: 1 }))).toThrow(
      'invalid config: headless',
    );
  });

  it('rejects a field of the wrong type', () => {
    expect(() =>
      readConfig(JSON.stringify({ baseUrl: 'x', retries: 'two', headless: true })),
    ).toThrow('invalid config: retries');
  });

  it('rejects invalid JSON', () => {
    expect(() => readConfig('{nope')).toThrow('invalid config: not JSON');
  });

  it('rejects JSON that is not an object', () => {
    expect(() => readConfig('42')).toThrow('invalid config: baseUrl');
  });
});

describe('11.3 satisfies', () => {
  it('returns a known environment', () => {
    expect(configFor('staging')).toEqual({
      baseUrl: 'https://staging.example.com',
      retries: 2,
    });
  });

  it('knows every environment', () => {
    expect(configFor('local').retries).toBe(0);
    expect(configFor('prod').retries).toBe(3);
  });

  it('rejects a typo at compile time', () => {
    // Graded by `npm run typecheck`, not by this line.
    // @ts-expect-error 'stagign' is not an environment.
    const attempt = () => configFor('stagign');
    void attempt;
    expect(true).toBe(true);
  });
});

describe('11.4 ownerEmail', () => {
  it('prefers the direct owner email', () => {
    expect(
      ownerEmail({
        suite: 's',
        owner: { email: 'ann@x.test', team: { lead: { email: 'lead@x.test' } } },
      }),
    ).toBe('ann@x.test');
  });

  it('falls back to the team lead', () => {
    expect(ownerEmail({ suite: 's', owner: { team: { lead: { email: 'lead@x.test' } } } })).toBe(
      'lead@x.test',
    );
  });

  it('falls back to unassigned', () => {
    expect(ownerEmail({ suite: 's' })).toBe('unassigned@example.com');
    expect(ownerEmail({ suite: 's', owner: {} })).toBe('unassigned@example.com');
    expect(ownerEmail({ suite: 's', owner: { team: {} } })).toBe('unassigned@example.com');
    expect(ownerEmail({ suite: 's', owner: { team: { lead: {} } } })).toBe(
      'unassigned@example.com',
    );
  });

  it('treats an empty string as a real value', () => {
    expect(ownerEmail({ suite: 's', owner: { email: '' } })).toBe('');
  });
});

describe('11.5 isTestRun / parseTestRuns', () => {
  const valid = { id: 'r1', suite: 'smoke', durationMs: 120, tags: ['fast'] };

  it('accepts a valid run', () => {
    expect(isTestRun(valid)).toBe(true);
  });

  it('accepts extra properties', () => {
    expect(isTestRun({ ...valid, retries: 3 })).toBe(true);
  });

  it('accepts an empty tag list', () => {
    expect(isTestRun({ ...valid, tags: [] })).toBe(true);
  });

  it('rejects wrong shapes', () => {
    expect(isTestRun(null)).toBe(false);
    expect(isTestRun([valid])).toBe(false);
    expect(isTestRun({ ...valid, id: 1 })).toBe(false);
    expect(isTestRun({ ...valid, durationMs: '120' })).toBe(false);
    expect(isTestRun({ ...valid, durationMs: NaN })).toBe(false);
    expect(isTestRun({ ...valid, tags: 'fast' })).toBe(false);
    expect(isTestRun({ ...valid, tags: ['fast', 2] })).toBe(false);
    const { suite: _dropped, ...withoutSuite } = valid;
    expect(isTestRun(withoutSuite)).toBe(false);
  });

  it('narrows, so the field access below needs no cast', () => {
    const value: unknown = valid;
    if (isTestRun(value)) {
      expect(value.suite.toUpperCase()).toBe('SMOKE');
    } else {
      expect.unreachable('should have been a TestRun');
    }
  });

  it('parses an array, dropping what does not fit', () => {
    const raw = JSON.stringify([valid, { id: 'r2' }, { ...valid, id: 'r3' }, null]);
    expect(parseTestRuns(raw).map((run) => run.id)).toEqual(['r1', 'r3']);
  });

  it('returns an empty array for junk', () => {
    expect(parseTestRuns('{nope')).toEqual([]);
    expect(parseTestRuns('{"a":1}')).toEqual([]);
    expect(parseTestRuns('[]')).toEqual([]);
  });
});
