/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import type { Expect, Equal } from '../_lib/type-assert';
import { FakeTransport } from '../_lib/fake-transport';
import {
  str,
  num,
  bool,
  arrayOf,
  optional,
  objectOf,
  oneOf,
  ApiClient,
  UsersApi,
  HttpError,
  SchemaError,
  userSchema,
  type User,
  type CreateUserInput,
} from './tasks';

const ann: User = {
  id: 1,
  email: 'ann@example.com',
  role: 'admin',
  tags: ['core'],
  nickname: undefined,
};

describe('13.1 primitives', () => {
  it('accepts the right type', () => {
    expect(str('x')).toEqual({ valid: true, value: 'x' });
    expect(num(42)).toEqual({ valid: true, value: 42 });
    expect(bool(false)).toEqual({ valid: true, value: false });
  });

  it('reports the wrong type with a path', () => {
    expect(str(42)).toEqual({ valid: false, errors: ['$: expected string, got number'] });
    expect(num('42', 'body.id')).toEqual({
      valid: false,
      errors: ['body.id: expected number, got string'],
    });
  });

  it('names null and arrays properly', () => {
    expect(str(null)).toEqual({ valid: false, errors: ['$: expected string, got null'] });
    expect(str([1])).toEqual({ valid: false, errors: ['$: expected string, got array'] });
    expect(str(undefined)).toEqual({
      valid: false,
      errors: ['$: expected string, got undefined'],
    });
  });

  it('rejects NaN as a number', () => {
    const result = num(Number.NaN);
    expect(result.valid).toBe(false);
  });
});

describe('13.1 arrayOf', () => {
  it('accepts a good array', () => {
    expect(arrayOf(str)(['a', 'b'])).toEqual({ valid: true, value: ['a', 'b'] });
    expect(arrayOf(num)([])).toEqual({ valid: true, value: [] });
  });

  it('rejects a non-array', () => {
    expect(arrayOf(str)('nope')).toEqual({
      valid: false,
      errors: ['$: expected array, got string'],
    });
  });

  it('reports every bad element with its index', () => {
    expect(arrayOf(str)(['a', 2, true])).toEqual({
      valid: false,
      errors: ['$[1]: expected string, got number', '$[2]: expected string, got boolean'],
    });
  });

  it('nests', () => {
    const result = arrayOf(arrayOf(num))([[1], ['x']]);
    expect(result).toEqual({
      valid: false,
      errors: ['$[1][0]: expected number, got string'],
    });
  });
});

describe('13.1 objectOf', () => {
  const schema = objectOf({ id: num, name: str });

  it('accepts a good object', () => {
    expect(schema({ id: 1, name: 'a' })).toEqual({ valid: true, value: { id: 1, name: 'a' } });
  });

  it('ignores extra properties', () => {
    const result = schema({ id: 1, name: 'a', extra: true });
    expect(result).toEqual({ valid: true, value: { id: 1, name: 'a' } });
  });

  it('reports every bad property in declaration order', () => {
    expect(schema({ id: 'x', name: 2 })).toEqual({
      valid: false,
      errors: ['$.id: expected number, got string', '$.name: expected string, got number'],
    });
  });

  it('reports missing properties', () => {
    expect(schema({})).toEqual({
      valid: false,
      errors: ['$.id: expected number, got undefined', '$.name: expected string, got undefined'],
    });
  });

  it('rejects things that are not objects', () => {
    expect(schema(null)).toEqual({ valid: false, errors: ['$: expected object, got null'] });
    expect(schema([])).toEqual({ valid: false, errors: ['$: expected object, got array'] });
    expect(schema(7)).toEqual({ valid: false, errors: ['$: expected object, got number'] });
  });

  it('nests with a path', () => {
    const nested = objectOf({ user: objectOf({ id: num }) });
    expect(nested({ user: { id: 'x' } })).toEqual({
      valid: false,
      errors: ['$.user.id: expected number, got string'],
    });
  });

  it('infers the object type', () => {
    const result = schema({ id: 1, name: 'a' });
    if (result.valid) {
      type _check = Expect<Equal<typeof result.value, { id: number; name: string }>>;
      expect(result.value.name.toUpperCase()).toBe('A');
    } else {
      expect.unreachable('should be valid');
    }
  });
});

describe('13.1 optional / oneOf', () => {
  it('optional accepts undefined', () => {
    expect(optional(str)(undefined)).toEqual({ valid: true, value: undefined });
  });

  it('optional still validates a present value', () => {
    expect(optional(str)('x')).toEqual({ valid: true, value: 'x' });
    expect(optional(str)(2)).toEqual({ valid: false, errors: ['$: expected string, got number'] });
  });

  it('optional works for a missing property', () => {
    const schema = objectOf({ id: num, nickname: optional(str) });
    expect(schema({ id: 1 })).toEqual({ valid: true, value: { id: 1, nickname: undefined } });
  });

  it('oneOf accepts a listed value', () => {
    expect(oneOf(['a', 'b'])('b')).toEqual({ valid: true, value: 'b' });
  });

  it('oneOf reports what was allowed', () => {
    expect(oneOf(['a', 'b'])('c')).toEqual({
      valid: false,
      errors: ['$: expected one of "a", "b", got "c"'],
    });
  });

  it('oneOf keeps the literal union type', () => {
    const result = oneOf(['admin', 'user'])('admin');
    if (result.valid) {
      type _check = Expect<Equal<typeof result.value, 'admin' | 'user'>>;
      expect(result.value).toBe('admin');
    } else {
      expect.unreachable('should be valid');
    }
  });
});

describe('13.2 ApiClient', () => {
  const okSchema = objectOf({ id: num });

  it('returns the validated body', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 200, body: { id: 1 } });
    const client = new ApiClient(transport);
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).resolves.toEqual({
      id: 1,
    });
  });

  it('sends the request as given', async () => {
    const transport = new FakeTransport().on('POST', '/x', { status: 201, body: { id: 2 } });
    const client = new ApiClient(transport);
    await client.request({ method: 'POST', path: '/x', body: { name: 'a' } }, okSchema);
    expect(transport.requests).toEqual([{ method: 'POST', path: '/x', body: { name: 'a' } }]);
  });

  it('accepts any 2xx', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 204, body: { id: 9 } });
    const client = new ApiClient(transport);
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).resolves.toEqual({
      id: 9,
    });
  });

  it('throws HttpError for a 4xx and does not retry it', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 404, body: null });
    const client = new ApiClient(transport);
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).rejects.toBeInstanceOf(
      HttpError,
    );
    expect(transport.countOf('GET', '/x')).toBe(1);
  });

  it('retries a 5xx and succeeds', async () => {
    const transport = new FakeTransport().on(
      'GET',
      '/x',
      { status: 503, body: null },
      { status: 200, body: { id: 3 } },
    );
    const client = new ApiClient(transport);
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).resolves.toEqual({
      id: 3,
    });
    expect(client.attempts).toBe(2);
  });

  it('gives up after the configured number of retries', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 500, body: null });
    const client = new ApiClient(transport, { retries: 2 });
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).rejects.toThrow(
      'HTTP 500 for /x',
    );
    expect(transport.countOf('GET', '/x')).toBe(3);
  });

  it('honours retries: 0', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 500, body: null });
    const client = new ApiClient(transport, { retries: 0 });
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).rejects.toThrow(
      HttpError,
    );
    expect(transport.countOf('GET', '/x')).toBe(1);
  });

  it('honours a custom retryOn', async () => {
    const transport = new FakeTransport().on(
      'GET',
      '/x',
      { status: 429, body: null },
      { status: 200, body: { id: 4 } },
    );
    const client = new ApiClient(transport, { retryOn: (status) => status === 429 });
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).resolves.toEqual({
      id: 4,
    });
  });

  it('throws SchemaError when the body is the wrong shape', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 200, body: { id: 'one' } });
    const client = new ApiClient(transport);
    const error = await client
      .request({ method: 'GET', path: '/x' }, okSchema)
      .catch((e: unknown) => e);
    expect(error).toBeInstanceOf(SchemaError);
    expect((error as SchemaError).errors).toEqual(['$.id: expected number, got string']);
  });

  it('does not retry a valid status with an invalid body', async () => {
    const transport = new FakeTransport().on('GET', '/x', { status: 200, body: {} });
    const client = new ApiClient(transport);
    await expect(client.request({ method: 'GET', path: '/x' }, okSchema)).rejects.toBeInstanceOf(
      SchemaError,
    );
    expect(transport.countOf('GET', '/x')).toBe(1);
  });
});

describe('13.3 UsersApi', () => {
  const transportWith = (body: unknown, method: 'GET' | 'POST' = 'GET', path = '/users') =>
    new FakeTransport().on(method, path, { status: 200, body });

  it('lists users', async () => {
    const api = new UsersApi(new ApiClient(transportWith([ann])));
    await expect(api.listUsers()).resolves.toEqual([ann]);
  });

  it('gets one user by id', async () => {
    const transport = transportWith(ann, 'GET', '/users/1');
    const api = new UsersApi(new ApiClient(transport));
    await expect(api.getUser(1)).resolves.toEqual(ann);
    expect(transport.requests[0]?.path).toBe('/users/1');
  });

  it('creates a user and sends the input as the body', async () => {
    const transport = transportWith(ann, 'POST', '/users');
    const api = new UsersApi(new ApiClient(transport));
    const input: CreateUserInput = { email: 'ann@example.com', role: 'admin' };
    await expect(api.createUser(input)).resolves.toEqual(ann);
    expect(transport.requests[0]).toEqual({ method: 'POST', path: '/users', body: input });
  });

  it('rejects a response that is not a user', async () => {
    const api = new UsersApi(new ApiClient(transportWith([{ id: 1 }])));
    await expect(api.listUsers()).rejects.toBeInstanceOf(SchemaError);
  });

  it('accepts a user with a nickname', async () => {
    const withNick = { ...ann, nickname: 'annie' };
    const api = new UsersApi(new ApiClient(transportWith(withNick, 'GET', '/users/1')));
    await expect(api.getUser(1)).resolves.toEqual(withNick);
  });

  it('rejects an unknown role', async () => {
    const api = new UsersApi(new ApiClient(transportWith({ ...ann, role: 'wizard' }, 'GET', '/users/1')));
    await expect(api.getUser(1)).rejects.toBeInstanceOf(SchemaError);
  });

  it('User is inferred from the schema', () => {
    type _check = Expect<
      Equal<
        User,
        {
          id: number;
          email: string;
          role: 'admin' | 'user' | 'guest';
          tags: string[];
          nickname: string | undefined;
        }
      >
    >;
    const result = userSchema(ann);
    expect(result.valid).toBe(true);
  });

  it('CreateUserInput is derived, not retyped', () => {
    type _check = Expect<
      Equal<
        CreateUserInput,
        {
          email: string;
          role: 'admin' | 'user' | 'guest';
          tags?: string[];
          nickname?: string | undefined;
        }
      >
    >;
    const input: CreateUserInput = { email: 'a@b.c', role: 'guest' };
    expect(input.role).toBe('guest');
  });
});
