/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect, vi } from 'vitest';
import { delay, withTimeout, retry, runAll, waitFor, mapWithConcurrency } from './tasks';

const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

describe('7.1 delay / withTimeout', () => {
  it('delay waits', async () => {
    const started = Date.now();
    await delay(40);
    expect(Date.now() - started).toBeGreaterThanOrEqual(30);
  });

  it('delay resolves with undefined', async () => {
    await expect(delay(1)).resolves.toBeUndefined();
  });

  it('withTimeout passes the value through when it is fast enough', async () => {
    await expect(withTimeout(Promise.resolve('ok'), 100, 'fast')).resolves.toBe('ok');
  });

  it('withTimeout propagates the original rejection', async () => {
    const failing = Promise.reject(new Error('boom'));
    // Silence Node's unhandled-rejection warning for the window before the
    // starter's `withTimeout` exists to attach its own handler. This does
    // not weaken the assertion below - `failing` is still the same rejected
    // promise, and `.rejects.toThrow` still requires withTimeout to surface it.
    failing.catch(() => undefined);
    await expect(withTimeout(failing, 100, 'failing')).rejects.toThrow('boom');
  });

  it('withTimeout rejects with the exact message', async () => {
    const slow = sleep(200).then(() => 'late');
    await expect(withTimeout(slow, 20, 'slow endpoint')).rejects.toThrow(
      'timed out after 20ms waiting for slow endpoint',
    );
  });

  it('withTimeout does not wait for the full timeout on success', async () => {
    const started = Date.now();
    await withTimeout(sleep(10).then(() => 1), 5_000, 'quick');
    expect(Date.now() - started).toBeLessThan(1_000);
  });
});

describe('7.2 retry', () => {
  it('returns the first successful value', async () => {
    const fn = vi.fn(async () => 'ok');
    await expect(retry(fn, { attempts: 3 })).resolves.toBe('ok');
    expect(fn).toHaveBeenCalledTimes(1);
  });

  it('retries until it succeeds', async () => {
    let calls = 0;
    const fn = async () => {
      calls += 1;
      if (calls < 3) throw new Error(`fail ${calls}`);
      return 'third time lucky';
    };
    await expect(retry(fn, { attempts: 5, delayMs: 1 })).resolves.toBe('third time lucky');
    expect(calls).toBe(3);
  });

  it('passes the 1-based attempt number', async () => {
    const seen: number[] = [];
    await expect(
      retry(
        async (attempt) => {
          seen.push(attempt);
          throw new Error('nope');
        },
        { attempts: 3, delayMs: 1 },
      ),
    ).rejects.toThrow('nope');
    expect(seen).toEqual([1, 2, 3]);
  });

  it('throws the last error, not a wrapper', async () => {
    let calls = 0;
    const fn = async () => {
      calls += 1;
      throw new Error(`failure ${calls}`);
    };
    await expect(retry(fn, { attempts: 2, delayMs: 1 })).rejects.toThrow('failure 2');
  });

  it('calls onRetry for every failure that is retried, and no more', async () => {
    const onRetry = vi.fn();
    await expect(
      retry(
        async () => {
          throw new Error('nope');
        },
        { attempts: 3, delayMs: 1, onRetry },
      ),
    ).rejects.toThrow();
    expect(onRetry).toHaveBeenCalledTimes(2);
    expect(onRetry.mock.calls[0]?.[1]).toBe(1);
    expect(onRetry.mock.calls[1]?.[1]).toBe(2);
  });

  it('does not sleep after the final attempt', async () => {
    const started = Date.now();
    await expect(
      retry(
        async () => {
          throw new Error('nope');
        },
        { attempts: 2, delayMs: 120 },
      ),
    ).rejects.toThrow();
    const elapsed = Date.now() - started;
    // One sleep of 120ms between the two attempts, not two.
    expect(elapsed).toBeLessThan(220);
    expect(elapsed).toBeGreaterThanOrEqual(100);
  });

  it('applies the backoff factor', async () => {
    const started = Date.now();
    await expect(
      retry(
        async () => {
          throw new Error('nope');
        },
        { attempts: 3, delayMs: 50, factor: 2 },
      ),
    ).rejects.toThrow();
    // 50 then 100 = 150ms of waiting.
    expect(Date.now() - started).toBeGreaterThanOrEqual(130);
  });

  it('rejects a nonsensical attempt count before calling fn', async () => {
    const fn = vi.fn(async () => 'never');
    await expect(retry(fn, { attempts: 0 })).rejects.toThrow(RangeError);
    expect(fn).not.toHaveBeenCalled();
  });
});

describe('7.3 runAll', () => {
  it('returns every result', async () => {
    const tasks = ['a', 'b', 'c'].map((value) => async () => {
      await sleep(5);
      return value;
    });
    await expect(runAll(tasks)).resolves.toEqual(['a', 'b', 'c']);
  });

  it('preserves order even when later tasks are faster', async () => {
    const tasks = [
      async () => {
        await sleep(30);
        return 'slow';
      },
      async () => {
        await sleep(1);
        return 'fast';
      },
    ];
    await expect(runAll(tasks)).resolves.toEqual(['slow', 'fast']);
  });

  it('runs them one at a time, not all at once', async () => {
    let inFlight = 0;
    let peak = 0;
    const tasks = [1, 2, 3].map((n) => async () => {
      inFlight += 1;
      peak = Math.max(peak, inFlight);
      await sleep(10);
      inFlight -= 1;
      return String(n);
    });
    await runAll(tasks);
    expect(peak).toBe(1);
  });

  it('handles an empty list', async () => {
    await expect(runAll([])).resolves.toEqual([]);
  });
});

describe('7.4 waitFor', () => {
  it('resolves immediately when the condition already holds', async () => {
    const started = Date.now();
    await waitFor(() => true, { intervalMs: 200 });
    expect(Date.now() - started).toBeLessThan(100);
  });

  it('polls until the condition becomes true', async () => {
    let ready = false;
    setTimeout(() => {
      ready = true;
    }, 60);
    await expect(waitFor(() => ready, { timeoutMs: 1_000, intervalMs: 10 })).resolves.toBeUndefined();
  });

  it('accepts an async predicate', async () => {
    let calls = 0;
    await waitFor(
      async () => {
        calls += 1;
        return calls >= 3;
      },
      { timeoutMs: 1_000, intervalMs: 5 },
    );
    expect(calls).toBe(3);
  });

  it('rejects with the exact message after the timeout', async () => {
    await expect(
      waitFor(() => false, { timeoutMs: 60, intervalMs: 10, label: 'cart badge' }),
    ).rejects.toThrow('condition not met within 60ms: cart badge');
  });

  it('uses the default label', async () => {
    await expect(waitFor(() => false, { timeoutMs: 40, intervalMs: 10 })).rejects.toThrow(
      'condition not met within 40ms: condition',
    );
  });

  it('treats a throwing predicate as "not yet"', async () => {
    let calls = 0;
    await waitFor(
      () => {
        calls += 1;
        if (calls < 3) throw new Error('element not attached');
        return true;
      },
      { timeoutMs: 1_000, intervalMs: 5 },
    );
    expect(calls).toBe(3);
  });

  it('gives up on a predicate that always throws', async () => {
    await expect(
      waitFor(
        () => {
          throw new Error('never attached');
        },
        { timeoutMs: 50, intervalMs: 10, label: 'x' },
      ),
    ).rejects.toThrow('condition not met within 50ms: x');
  });
});

describe('7.5 mapWithConcurrency', () => {
  it('maps every item in input order', async () => {
    const items = [1, 2, 3, 4, 5];
    const result = await mapWithConcurrency(items, 2, async (n) => {
      await sleep(10 - n);
      return n * 2;
    });
    expect(result).toEqual([2, 4, 6, 8, 10]);
  });

  it('passes the index', async () => {
    const result = await mapWithConcurrency(['a', 'b'], 1, async (item, index) => `${index}:${item}`);
    expect(result).toEqual(['0:a', '1:b']);
  });

  it('never exceeds the limit', async () => {
    let inFlight = 0;
    let peak = 0;
    await mapWithConcurrency([...Array(10).keys()], 3, async (n) => {
      inFlight += 1;
      peak = Math.max(peak, inFlight);
      await sleep(10);
      inFlight -= 1;
      return n;
    });
    expect(peak).toBeLessThanOrEqual(3);
    expect(peak).toBeGreaterThan(1);
  });

  it('actually runs in parallel up to the limit', async () => {
    const started = Date.now();
    await mapWithConcurrency([...Array(6).keys()], 3, async () => {
      await sleep(30);
      return 1;
    });
    // Six 30ms tasks, three at a time = two waves ~= 60ms, not 180ms.
    expect(Date.now() - started).toBeLessThan(150);
  });

  it('rejects when a task rejects', async () => {
    await expect(
      mapWithConcurrency([1, 2, 3], 2, async (n) => {
        if (n === 2) throw new Error('item 2 exploded');
        return n;
      }),
    ).rejects.toThrow('item 2 exploded');
  });

  it('refuses a limit below one', async () => {
    await expect(mapWithConcurrency([1], 0, async (n) => n)).rejects.toThrow(RangeError);
  });

  it('handles an empty input without calling fn', async () => {
    const fn = vi.fn(async (n: number) => n);
    await expect(mapWithConcurrency([], 2, fn)).resolves.toEqual([]);
    expect(fn).not.toHaveBeenCalled();
  });
});
