/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 *
 *  Most of module 10 is graded by `npm run typecheck`, not by these
 *  tests - types do not exist at runtime, so there is nothing here
 *  to execute for them. The tests below cover the parts that do run,
 *  and give every task a row in your progress report.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import type { Expect, Equal } from '../_lib/type-assert';
import {
  STATUS_COLORS,
  colorFor,
  statusNames,
  testId,
  type TestRunKey,
  type TestRunPatch,
  type StatusName,
  type Nullable,
  type DeepPartial,
  type UnwrapPromise,
} from './tasks';

describe('10.1 utility types', () => {
  it('is graded by the type checker', () => {
    // A value typed with your derived types. If `TestRunKey` is still
    // `never`, this line does not compile.
    const key: TestRunKey = { id: 'r1', suite: 'smoke' };
    const patch: TestRunPatch = { suite: 'regression' };
    expect(key.id).toBe('r1');
    expect(patch.suite).toBe('regression');
  });

  it('a patch may be completely empty', () => {
    const patch: TestRunPatch = {};
    expect(Object.keys(patch)).toEqual([]);
  });
});

describe('10.2 keyof / typeof', () => {
  it('maps a status to a colour', () => {
    expect(colorFor('passed')).toBe('green');
    expect(colorFor('failed')).toBe('red');
    expect(colorFor('skipped')).toBe('grey');
    expect(colorFor('flaky')).toBe('amber');
  });

  it('lists every status', () => {
    expect(statusNames().sort()).toEqual(['failed', 'flaky', 'passed', 'skipped']);
  });

  it('stays in sync with the constant', () => {
    expect(statusNames().sort()).toEqual(Object.keys(STATUS_COLORS).sort());
  });

  it('rejects a status that is not in the object', () => {
    // Graded by `npm run typecheck`, not by this line.
    // @ts-expect-error 'exploded' is not a key of STATUS_COLORS.
    const attempt = () => colorFor('exploded');
    void attempt;
    expect(true).toBe(true);
  });

  it('gives colorFor a narrow return type', () => {
    const color = colorFor('passed');
    type _check = Expect<Equal<typeof color, 'green' | 'red' | 'grey' | 'amber'>>;
    expect(color).toBe('green');
  });
});

describe('10.3 mapped types', () => {
  it('is graded by the type checker', () => {
    const nullable: Nullable<{ a: string }> = { a: null };
    const deep: DeepPartial<{ a: { b: string } }> = { a: {} };
    expect(nullable.a).toBeNull();
    expect(deep.a).toEqual({});
  });
});

describe('10.4 conditional types', () => {
  it('is graded by the type checker', async () => {
    const value: UnwrapPromise<Promise<number>> = 42;
    expect(value).toBe(42);
  });
});

describe('10.5 template literal types', () => {
  it('builds a selector', () => {
    expect(testId('cart')).toBe('[data-testid="cart"]');
    expect(testId('checkout-submit')).toBe('[data-testid="checkout-submit"]');
  });

  it('keeps the literal type, not plain string', () => {
    const selector = testId('cart');
    type _check = Expect<Equal<typeof selector, '[data-testid="cart"]'>>;
    expect(selector).toContain('cart');
  });
});

describe('10 status names are usable as a type', () => {
  it('accepts every real status', () => {
    const names: StatusName[] = ['passed', 'failed', 'skipped', 'flaky'];
    expect(names).toHaveLength(4);
  });
});
