/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import {
  uniqueBy,
  partition,
  sortBy,
  slowestTests,
  medianDuration,
  summarize,
  diffSuites,
  type TestResult,
} from './tasks';

const r = (name: string, status: TestResult['status'], durationMs: number): TestResult => ({
  name,
  status,
  durationMs,
});

const sample: TestResult[] = [
  r('login', 'passed', 1200),
  r('checkout', 'failed', 300),
  r('search', 'passed', 4500),
  r('refund', 'skipped', 0),
  r('cart', 'flaky', 800),
];

describe('6.1 uniqueBy / partition', () => {
  it('keeps the first occurrence of each key', () => {
    const items = [r('a', 'passed', 1), r('b', 'failed', 2), r('a', 'failed', 3)];
    expect(uniqueBy(items, (x) => x.name).map((x) => x.durationMs)).toEqual([1, 2]);
  });

  it('leaves the input alone', () => {
    const items = [r('a', 'passed', 1), r('a', 'failed', 3)];
    uniqueBy(items, (x) => x.name);
    expect(items).toHaveLength(2);
  });

  it('partitions into matching and the rest', () => {
    const [failures, rest] = partition(sample, (x) => x.status === 'failed');
    expect(failures.map((x) => x.name)).toEqual(['checkout']);
    expect(rest).toHaveLength(4);
  });

  it('returns two empty arrays for an empty input', () => {
    expect(partition([], () => true)).toEqual([[], []]);
  });

  it('handles an all-or-nothing predicate', () => {
    const [all, none] = partition(sample, () => true);
    expect(all).toHaveLength(5);
    expect(none).toEqual([]);
  });
});

describe('6.2 sortBy', () => {
  it('sorts by one numeric key', () => {
    expect(sortBy(sample, [(x) => x.durationMs]).map((x) => x.name)).toEqual([
      'refund',
      'checkout',
      'cart',
      'login',
      'search',
    ]);
  });

  it('sorts by one string key', () => {
    expect(sortBy(sample, [(x) => x.name]).map((x) => x.name)).toEqual([
      'cart',
      'checkout',
      'login',
      'refund',
      'search',
    ]);
  });

  it('breaks ties with the second selector', () => {
    const items = [
      r('c', 'passed', 300),
      r('a', 'failed', 100),
      r('b', 'passed', 100),
      r('d', 'failed', 50),
    ];
    expect(sortBy(items, [(x) => x.status, (x) => x.durationMs]).map((x) => x.name)).toEqual([
      'd',
      'a',
      'b',
      'c',
    ]);
  });

  it('is stable', () => {
    const items = [r('x', 'passed', 1), r('y', 'passed', 1), r('z', 'passed', 1)];
    expect(sortBy(items, [(i) => i.durationMs]).map((i) => i.name)).toEqual(['x', 'y', 'z']);
  });

  it('does not mutate the input', () => {
    const items = [r('b', 'passed', 2), r('a', 'passed', 1)];
    const snapshot = items.map((i) => i.name);
    sortBy(items, [(i) => i.name]);
    expect(items.map((i) => i.name)).toEqual(snapshot);
  });

  it('with no selectors returns a copy in original order', () => {
    const copy = sortBy(sample, []);
    expect(copy.map((x) => x.name)).toEqual(sample.map((x) => x.name));
    expect(copy).not.toBe(sample);
  });
});

describe('6.3 slowestTests / medianDuration', () => {
  it('returns the N slowest, slowest first', () => {
    expect(slowestTests(sample, 2).map((x) => x.name)).toEqual(['search', 'login']);
  });

  it('copes with N larger than the array', () => {
    expect(slowestTests(sample, 99)).toHaveLength(5);
  });

  it('does not reorder the caller array', () => {
    const items = [r('a', 'passed', 1), r('b', 'passed', 9), r('c', 'passed', 5)];
    slowestTests(items, 2);
    expect(items.map((x) => x.name)).toEqual(['a', 'b', 'c']);
  });

  it('finds the median of an odd number of results', () => {
    const items = [r('a', 'passed', 1), r('b', 'passed', 2), r('c', 'passed', 10)];
    expect(medianDuration(items)).toBe(2);
  });

  it('averages the middle two for an even number of results', () => {
    const items = [
      r('a', 'passed', 1),
      r('b', 'passed', 3),
      r('c', 'passed', 10),
      r('d', 'passed', 200),
    ];
    expect(medianDuration(items)).toBe(6.5);
  });

  it('handles unsorted input', () => {
    const items = [r('a', 'passed', 300), r('b', 'passed', 9), r('c', 'passed', 100)];
    expect(medianDuration(items)).toBe(100);
  });

  it('returns 0 for an empty run', () => {
    expect(medianDuration([])).toBe(0);
  });
});

describe('6.4 summarize', () => {
  it('counts every status', () => {
    const summary = summarize(sample);
    expect(summary.total).toBe(5);
    expect(summary.passed).toBe(2);
    expect(summary.failed).toBe(1);
    expect(summary.skipped).toBe(1);
    expect(summary.flaky).toBe(1);
  });

  it('excludes skipped tests from the pass rate', () => {
    // 2 passed out of 4 non-skipped
    expect(summarize(sample).passRate).toBe(0.5);
  });

  it('rounds the pass rate to two decimals', () => {
    const items = [
      r('a', 'passed', 1),
      r('b', 'passed', 1),
      r('c', 'failed', 1),
      r('d', 'passed', 1),
      r('e', 'passed', 1),
      r('f', 'failed', 1),
      r('g', 'passed', 1),
    ];
    // 5 / 7 = 0.714285...
    expect(summarize(items).passRate).toBe(0.71);
  });

  it('reports 0 rather than NaN when everything was skipped', () => {
    expect(summarize([r('a', 'skipped', 0)]).passRate).toBe(0);
  });

  it('sums durations and names the slowest', () => {
    const summary = summarize(sample);
    expect(summary.totalDurationMs).toBe(6800);
    expect(summary.slowest).toBe('search');
  });

  it('gives the first name on a tie', () => {
    const items = [r('a', 'passed', 5), r('b', 'passed', 5)];
    expect(summarize(items).slowest).toBe('a');
  });

  it('handles an empty run without dividing by zero', () => {
    expect(summarize([])).toEqual({
      total: 0,
      passed: 0,
      failed: 0,
      skipped: 0,
      flaky: 0,
      passRate: 0,
      totalDurationMs: 0,
      slowest: null,
    });
  });
});

describe('6.5 diffSuites', () => {
  it('finds added, removed and common names', () => {
    expect(diffSuites(['a', 'b', 'c'], ['b', 'c', 'd'])).toEqual({
      added: ['d'],
      removed: ['a'],
      common: ['b', 'c'],
    });
  });

  it('preserves the source order of each list', () => {
    expect(diffSuites(['z', 'a'], ['q', 'a', 'b'])).toEqual({
      added: ['q', 'b'],
      removed: ['z'],
      common: ['a'],
    });
  });

  it('handles identical suites', () => {
    expect(diffSuites(['a'], ['a'])).toEqual({ added: [], removed: [], common: ['a'] });
  });

  it('handles empty inputs', () => {
    expect(diffSuites([], [])).toEqual({ added: [], removed: [], common: [] });
    expect(diffSuites([], ['a'])).toEqual({ added: ['a'], removed: [], common: [] });
  });

  it('deduplicates repeated names', () => {
    expect(diffSuites(['a', 'a'], ['a', 'b', 'b'])).toEqual({
      added: ['b'],
      removed: [],
      common: ['a'],
    });
  });
});
