/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect, vi } from 'vitest';
import {
  TimeoutError,
  HttpError,
  ValidationError,
  toError,
  withCleanup,
  success,
  failure,
  attempt,
  attemptAsync,
  unwrapOr,
  wrapError,
  rootCause,
  describeChain,
  type Result,
} from './tasks';

describe('8.1 custom errors', () => {
  it('TimeoutError carries its message, name and data', () => {
    const error = new TimeoutError(5000, 'cart badge');
    expect(error.message).toBe('timed out after 5000ms waiting for cart badge');
    expect(error.name).toBe('TimeoutError');
    expect(error.timeoutMs).toBe(5000);
  });

  it('HttpError carries the status and url', () => {
    const error = new HttpError(404, 'https://api.test/users/9');
    expect(error.message).toBe('HTTP 404 for https://api.test/users/9');
    expect(error.name).toBe('HttpError');
    expect(error.status).toBe(404);
    expect(error.url).toBe('https://api.test/users/9');
  });

  it('ValidationError lists its fields', () => {
    const error = new ValidationError(['email', 'age']);
    expect(error.message).toBe('invalid fields: email, age');
    expect(error.name).toBe('ValidationError');
    expect(error.fields).toEqual(['email', 'age']);
  });

  it('every one of them is a real Error', () => {
    expect(new TimeoutError(1, 'x')).toBeInstanceOf(Error);
    expect(new HttpError(500, 'u')).toBeInstanceOf(Error);
    expect(new ValidationError([])).toBeInstanceOf(Error);
  });

  it('instanceof distinguishes them, which is the whole point', () => {
    const error: Error = new HttpError(503, 'https://api.test');
    expect(error instanceof HttpError).toBe(true);
    expect(error instanceof TimeoutError).toBe(false);
  });

  it('has a stack trace', () => {
    expect(typeof new TimeoutError(1, 'x').stack).toBe('string');
  });
});

describe('8.2 toError', () => {
  it('returns an Error untouched', () => {
    const original = new Error('boom');
    expect(toError(original)).toBe(original);
  });

  it('keeps subclasses intact', () => {
    const original = new HttpError(500, 'u');
    expect(toError(original)).toBe(original);
  });

  it('wraps a string', () => {
    expect(toError('boom').message).toBe('boom');
  });

  it('uses a message property when there is one', () => {
    expect(toError({ message: 'oops' }).message).toBe('oops');
  });

  it('stringifies anything else', () => {
    expect(toError(42).message).toBe('42');
    expect(toError(null).message).toBe('null');
    expect(toError(undefined).message).toBe('undefined');
    expect(toError({ a: 1 }).message).toBe('{"a":1}');
  });

  it('survives a value that cannot be serialised', () => {
    const circular: Record<string, unknown> = {};
    circular['self'] = circular;
    expect(() => toError(circular)).not.toThrow();
    expect(toError(circular)).toBeInstanceOf(Error);
  });
});

describe('8.3 withCleanup', () => {
  it('returns the value on success', async () => {
    await expect(withCleanup(async () => 'ok', () => undefined)).resolves.toBe('ok');
  });

  it('runs cleanup after the work finishes, not before', async () => {
    const order: string[] = [];
    await withCleanup(
      async () => {
        await new Promise((r) => setTimeout(r, 10));
        order.push('work');
        return 1;
      },
      () => order.push('cleanup'),
    );
    expect(order).toEqual(['work', 'cleanup']);
  });

  it('runs cleanup when the work fails', async () => {
    const cleanup = vi.fn();
    await expect(
      withCleanup(async () => {
        throw new Error('work failed');
      }, cleanup),
    ).rejects.toThrow('work failed');
    expect(cleanup).toHaveBeenCalledTimes(1);
  });

  it('runs cleanup exactly once on success', async () => {
    const cleanup = vi.fn();
    await withCleanup(async () => 'ok', cleanup);
    expect(cleanup).toHaveBeenCalledTimes(1);
  });

  it('preserves the original error type', async () => {
    const cleanup = vi.fn();
    await expect(
      withCleanup(async () => {
        throw new HttpError(500, 'https://api.test');
      }, cleanup),
    ).rejects.toBeInstanceOf(HttpError);
    expect(cleanup).toHaveBeenCalledTimes(1);
  });
});

describe('8.4 Result', () => {
  it('builds successes and failures', () => {
    expect(success(1)).toEqual({ ok: true, value: 1 });
    const error = new Error('x');
    expect(failure(error)).toEqual({ ok: false, error });
  });

  it('attempt captures a return value', () => {
    const result = attempt(() => 2 + 2);
    expect(result).toEqual({ ok: true, value: 4 });
  });

  it('attempt captures a throw', () => {
    const result = attempt(() => {
      throw new Error('nope');
    });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error.message).toBe('nope');
  });

  it('attempt normalises a thrown string', () => {
    const result = attempt(() => {
      throw 'just a string';
    });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toBeInstanceOf(Error);
      expect(result.error.message).toBe('just a string');
    }
  });

  it('attemptAsync captures a resolved value', async () => {
    await expect(attemptAsync(async () => 'ok')).resolves.toEqual({ ok: true, value: 'ok' });
  });

  it('attemptAsync captures a rejection', async () => {
    const result = await attemptAsync(async () => {
      throw new HttpError(500, 'https://api.test');
    });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error).toBeInstanceOf(HttpError);
  });

  it('unwrapOr returns the value or the fallback', () => {
    expect(unwrapOr(success(7), 0)).toBe(7);
    const failed: Result<number> = failure(new Error('x'));
    expect(unwrapOr(failed, 0)).toBe(0);
  });

  it('narrows on the ok discriminant', () => {
    const result = attempt(() => 'value');
    if (result.ok) {
      // `.value` is only reachable in this branch, with no cast.
      expect(result.value.toUpperCase()).toBe('VALUE');
    } else {
      expect.unreachable('should have succeeded');
    }
  });
});

describe('8.5 error chains', () => {
  it('wrapError keeps the cause', () => {
    const original = new HttpError(500, 'https://api.test/seed');
    const wrapped = wrapError('loading fixtures failed', original);
    expect(wrapped.message).toBe('loading fixtures failed');
    expect(wrapped.cause).toBe(original);
  });

  it('rootCause returns the error itself when there is no cause', () => {
    const error = new Error('alone');
    expect(rootCause(error)).toBe(error);
  });

  it('rootCause walks to the bottom', () => {
    const root = new Error('ECONNREFUSED 127.0.0.1:5432');
    const middle = wrapError('could not seed database', root);
    const top = wrapError('suite setup failed', middle);
    expect(rootCause(top)).toBe(root);
  });

  it('describeChain reads outermost first', () => {
    const root = new Error('ECONNREFUSED');
    const top = wrapError('suite setup failed', wrapError('could not seed database', root));
    expect(describeChain(top)).toBe(
      'suite setup failed <- could not seed database <- ECONNREFUSED',
    );
  });

  it('describeChain of a lone error is just its message', () => {
    expect(describeChain(new Error('alone'))).toBe('alone');
  });

  it('stops at a non-Error cause', () => {
    const error = new Error('outer', { cause: 'a plain string' });
    expect(rootCause(error)).toBe(error);
    expect(describeChain(error)).toBe('outer');
  });
});
