/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import {
  formatStep,
  assertNever,
  exitCodeFor,
  isFailed,
  failedSteps,
  firstErrorMessage,
  describeValue,
  assertIsString,
  upperCaseAll,
  type StepResult,
} from './tasks';

const passed = { kind: 'passed', name: 'login', durationMs: 1234 } as StepResult;
const failed = {
  kind: 'failed',
  name: 'checkout',
  durationMs: 812,
  error: 'expected 200, got 500',
} as StepResult;
const skipped = {
  kind: 'skipped',
  name: 'refund',
  reason: 'no test account on staging',
} as StepResult;

describe('4.1 formatStep', () => {
  it('formats a passed step', () => {
    expect(formatStep(passed)).toBe('PASS login (1234ms)');
  });

  it('formats a failed step with its error', () => {
    expect(formatStep(failed)).toBe('FAIL checkout (812ms): expected 200, got 500');
  });

  it('formats a skipped step with its reason, and no duration', () => {
    expect(formatStep(skipped)).toBe('SKIP refund: no test account on staging');
  });
});

describe('4.2 exhaustiveness', () => {
  it('maps kinds to exit codes', () => {
    expect(exitCodeFor(passed)).toBe(0);
    expect(exitCodeFor(skipped)).toBe(0);
    expect(exitCodeFor(failed)).toBe(1);
  });

  it('throws if a value sneaks past the type system at runtime', () => {
    const smuggled = { kind: 'exploded', name: 'x' } as unknown as StepResult;
    expect(() => exitCodeFor(smuggled)).toThrow(TypeError);
  });

  it('puts the offending value in the message', () => {
    const smuggled = { kind: 'exploded', name: 'x' } as unknown as StepResult;
    expect(() => exitCodeFor(smuggled)).toThrow(/exploded/);
  });

  it('refuses a non-never argument at compile time', () => {
    // @ts-expect-error assertNever only accepts `never`.
    expect(() => assertNever('definitely reachable')).toBeDefined();
  });
});

describe('4.3 isFailed', () => {
  const alsoFailed = {
    kind: 'failed',
    name: 'refund',
    durationMs: 10,
    error: 'timeout',
  } as StepResult;
  const steps = [passed, failed, skipped, alsoFailed];

  it('identifies failed steps', () => {
    expect(isFailed(passed)).toBe(false);
    expect(isFailed(failed)).toBe(true);
    expect(isFailed(skipped)).toBe(false);
  });

  it('filters down to failures', () => {
    expect(failedSteps(steps)).toHaveLength(2);
    expect(failedSteps([passed, skipped])).toEqual([]);
  });

  it('narrows the array element type, so `.error` is reachable without a cast', () => {
    // This line does not compile while `isFailed` returns plain `boolean`.
    const errors = failedSteps(steps).map((step) => step.error);
    expect(errors).toEqual(['expected 200, got 500', 'timeout']);
  });

  it('returns the first error message', () => {
    expect(firstErrorMessage(steps)).toBe('expected 200, got 500');
  });

  it('returns null when nothing failed', () => {
    expect(firstErrorMessage([passed, skipped])).toBeNull();
  });
});

describe('4.4 describeValue', () => {
  it('describes null without exploding', () => {
    expect(describeValue(null)).toBe('null');
  });

  it('describes undefined', () => {
    expect(describeValue(undefined)).toBe('undefined');
  });

  it('describes arrays with their length', () => {
    expect(describeValue([1, 2, 3])).toBe('array(3)');
    expect(describeValue([])).toBe('array(0)');
  });

  it('describes plain objects with their key count', () => {
    expect(describeValue({ a: 1 })).toBe('object{1}');
    expect(describeValue({})).toBe('object{0}');
  });

  it('describes primitives', () => {
    expect(describeValue('hello')).toBe('string');
    expect(describeValue(42)).toBe('number');
    expect(describeValue(true)).toBe('boolean');
  });

  it('describes functions', () => {
    expect(describeValue(() => undefined)).toBe('function');
  });
});

describe('4.5 assertIsString', () => {
  it('passes a string through', () => {
    expect(() => assertIsString('ok', 'value')).not.toThrow();
  });

  it('throws a TypeError with the exact message', () => {
    expect(() => assertIsString(42, 'retries')).toThrow(TypeError);
    expect(() => assertIsString(42, 'retries')).toThrow('retries must be a string, got number');
    expect(() => assertIsString(null, 'name')).toThrow('name must be a string, got object');
  });

  it('narrows the variable for the rest of the scope', () => {
    const value: unknown = 'hello';
    assertIsString(value, 'value');
    // The next line is a compile error until `assertIsString` returns
    // `asserts value is string`. `npm test` alone will not tell you.
    expect(value.toUpperCase()).toBe('HELLO');
  });

  it('upperCaseAll maps strings', () => {
    expect(upperCaseAll(['a', 'b'])).toEqual(['A', 'B']);
    expect(upperCaseAll([])).toEqual([]);
  });

  it('upperCaseAll reports the index of the first offender', () => {
    expect(() => upperCaseAll(['a', 1, 'c'])).toThrow('values[1] must be a string, got number');
  });
});
