/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect, vi } from 'vitest';
import {
  UserBuilder,
  DEFAULT_USER,
  makeUser,
  withFixture,
  withFixtures,
  SoftAssert,
  type Fixture,
} from './tasks';

describe('12.1 UserBuilder', () => {
  it('builds a sensible default user', () => {
    expect(UserBuilder.aUser().build()).toEqual({
      id: 1,
      email: 'user1@example.com',
      role: 'user',
      active: true,
      tags: [],
    });
  });

  it('chains', () => {
    const user = UserBuilder.aUser().withId(7).asAdmin().inactive().withTag('vip').build();
    expect(user).toEqual({
      id: 7,
      email: 'user7@example.com',
      role: 'admin',
      active: false,
      tags: ['vip'],
    });
  });

  it('lets an explicit email survive a later withId', () => {
    const user = UserBuilder.aUser().withEmail('me@x.test').withId(9).build();
    expect(user.email).toBe('me@x.test');
    expect(user.id).toBe(9);
  });

  it('accumulates tags', () => {
    expect(UserBuilder.aUser().withTag('a').withTag('b').build().tags).toEqual(['a', 'b']);
  });

  it('builds independent objects', () => {
    const builder = UserBuilder.aUser().withTag('a');
    const first = builder.build();
    const second = builder.build();
    expect(first).toEqual(second);
    expect(first).not.toBe(second);
    expect(first.tags).not.toBe(second.tags);
  });

  it('is not corrupted by mutating what it built', () => {
    const builder = UserBuilder.aUser();
    const first = builder.build();
    first.tags.push('injected');
    first.email = 'changed@x.test';
    expect(builder.build()).toEqual({
      id: 1,
      email: 'user1@example.com',
      role: 'user',
      active: true,
      tags: [],
    });
  });

  it('buildMany counts ids up', () => {
    const users = UserBuilder.aUser().withId(10).asAdmin().buildMany(3);
    expect(users.map((u) => u.id)).toEqual([10, 11, 12]);
    expect(users.map((u) => u.email)).toEqual([
      'user10@example.com',
      'user11@example.com',
      'user12@example.com',
    ]);
    expect(users.every((u) => u.role === 'admin')).toBe(true);
  });

  it('buildMany keeps an explicit email for everyone', () => {
    const users = UserBuilder.aUser().withEmail('shared@x.test').buildMany(2);
    expect(users.map((u) => u.email)).toEqual(['shared@x.test', 'shared@x.test']);
  });

  it('cannot be constructed directly', () => {
    // @ts-expect-error the constructor is private; use UserBuilder.aUser().
    expect(() => new UserBuilder()).toBeDefined();
  });
});

describe('12.2 makeUser', () => {
  it('applies overrides', () => {
    expect(makeUser({ role: 'admin' }).role).toBe('admin');
  });

  it('does not leak overrides into the next call', () => {
    makeUser({ role: 'admin', id: 99 });
    const plain = makeUser();
    expect(plain.role).toBe('user');
    expect(plain.id).toBe(1);
  });

  it('leaves DEFAULT_USER alone', () => {
    makeUser({ role: 'guest', active: false, id: 42 });
    expect(DEFAULT_USER).toEqual({
      id: 1,
      email: 'user1@example.com',
      role: 'user',
      active: true,
      tags: [],
    });
  });

  it('gives every user its own tags array', () => {
    const a = makeUser();
    const b = makeUser();
    a.tags.push('a-only');
    expect(b.tags).toEqual([]);
    expect(DEFAULT_USER.tags).toEqual([]);
  });

  it('returns a new object each time', () => {
    expect(makeUser()).not.toBe(makeUser());
  });
});

describe('12.3 fixtures', () => {
  const trackingFixture = (name: string, log: string[]): Fixture<string> => ({
    name,
    setup: async () => {
      log.push(`setup ${name}`);
      return name;
    },
    teardown: async (value) => {
      log.push(`teardown ${value}`);
    },
  });

  it('sets up, uses and tears down', async () => {
    const log: string[] = [];
    const result = await withFixture(trackingFixture('db', log), async (value) => {
      log.push(`use ${value}`);
      return `${value}!`;
    });
    expect(result).toBe('db!');
    expect(log).toEqual(['setup db', 'use db', 'teardown db']);
  });

  it('tears down when the body throws, and re-throws', async () => {
    const log: string[] = [];
    await expect(
      withFixture(trackingFixture('db', log), async () => {
        throw new Error('test failed');
      }),
    ).rejects.toThrow('test failed');
    expect(log).toEqual(['setup db', 'teardown db']);
  });

  it('surfaces a teardown failure when the body succeeded', async () => {
    const fixture: Fixture<number> = {
      name: 'leaky',
      setup: async () => 1,
      teardown: async () => {
        throw new Error('teardown exploded');
      },
    };
    await expect(withFixture(fixture, async () => 'fine')).rejects.toThrow(
      'teardown exploded',
    );
  });

  it('never lets a teardown failure hide a test failure', async () => {
    const fixture: Fixture<number> = {
      name: 'leaky',
      setup: async () => 1,
      teardown: async () => {
        throw new Error('teardown exploded');
      },
    };
    await expect(
      withFixture(fixture, async () => {
        throw new Error('the real failure');
      }),
    ).rejects.toThrow('the real failure');
  });

  it('sets up in order and tears down in reverse', async () => {
    const log: string[] = [];
    const values = await withFixtures(
      [trackingFixture('a', log), trackingFixture('b', log), trackingFixture('c', log)],
      async (vals) => {
        log.push('use');
        return vals;
      },
    );
    expect(values).toEqual(['a', 'b', 'c']);
    expect(log).toEqual([
      'setup a',
      'setup b',
      'setup c',
      'use',
      'teardown c',
      'teardown b',
      'teardown a',
    ]);
  });

  it('tears down what was already built when a setup fails', async () => {
    const log: string[] = [];
    const exploding: Fixture<string> = {
      name: 'boom',
      setup: async () => {
        throw new Error('setup failed');
      },
      teardown: async () => {
        log.push('teardown boom');
      },
    };
    const use = vi.fn(async () => 'never');
    await expect(
      withFixtures([trackingFixture('a', log), exploding, trackingFixture('c', log)], use),
    ).rejects.toThrow('setup failed');
    expect(log).toEqual(['setup a', 'teardown a']);
    expect(use).not.toHaveBeenCalled();
  });

  it('handles an empty fixture list', async () => {
    await expect(withFixtures([], async (values) => values.length)).resolves.toBe(0);
  });
});

describe('12.4 SoftAssert', () => {
  it('collects nothing when everything passes', () => {
    const soft = new SoftAssert();
    soft.check('a', true).equal('b', 1, 1);
    expect(soft.failures).toEqual([]);
    expect(() => soft.assertAll()).not.toThrow();
  });

  it('records a failed check by its label', () => {
    const soft = new SoftAssert();
    soft.check('cart badge is visible', false);
    expect(soft.failures).toEqual(['cart badge is visible']);
  });

  it('formats a failed equality', () => {
    const soft = new SoftAssert();
    soft.equal('total', 41, 42);
    expect(soft.failures).toEqual(['total: expected 42, got 41']);
  });

  it('stringifies non-primitives', () => {
    const soft = new SoftAssert();
    soft.equal('name', 'ann', 'bo');
    expect(soft.failures).toEqual(['name: expected "bo", got "ann"']);
  });

  it('chains', () => {
    const soft = new SoftAssert();
    expect(soft.check('a', false).check('b', false)).toBe(soft);
    expect(soft.failures).toHaveLength(2);
  });

  it('hands out a copy of the failures', () => {
    const soft = new SoftAssert();
    soft.check('a', false);
    (soft.failures as string[]).push('injected');
    expect(soft.failures).toEqual(['a']);
  });

  it('throws one error listing everything', () => {
    const soft = new SoftAssert();
    soft.check('first', false).check('second', false).check('third', false);
    expect(() => soft.assertAll()).toThrow(
      '3 soft assertion(s) failed:\n  - first\n  - second\n  - third',
    );
  });

  it('clears after assertAll so the instance is reusable', () => {
    const soft = new SoftAssert();
    soft.check('first', false);
    expect(() => soft.assertAll()).toThrow();
    expect(soft.failures).toEqual([]);
    expect(() => soft.assertAll()).not.toThrow();
  });
});
