/* =============================================================== *
 *  DO NOT EDIT THIS FILE.
 * =============================================================== */

import { describe, it, expect } from 'vitest';
import {
  formatTestCase,
  countByStatus,
  cloneConfig,
  mergeConfig,
  createReporter,
  type TestCase,
  type SuiteConfig,
} from './tasks';

const base = (over: Partial<TestCase> = {}): TestCase =>
  ({
    id: 'TC-1',
    title: 'Login works',
    status: 'passed',
    durationMs: 1234,
    ...over,
  }) as TestCase;

describe('3.1 formatTestCase', () => {
  it('renders the four mandatory parts', () => {
    expect(formatTestCase(base())).toBe('TC-1 · Login works · passed · 1.2s');
  });

  it('renders sub-second durations in milliseconds', () => {
    expect(formatTestCase(base({ status: 'failed', durationMs: 950 }))).toBe(
      'TC-1 · Login works · failed · 950ms',
    );
  });

  it('renders exactly one decimal for seconds', () => {
    expect(formatTestCase(base({ durationMs: 2000 }))).toContain('2.0s');
    expect(formatTestCase(base({ durationMs: 1000 }))).toContain('1.0s');
  });

  it('appends tags when there are any', () => {
    expect(formatTestCase(base({ tags: ['smoke', 'auth'] }))).toBe(
      'TC-1 · Login works · passed · 1.2s [smoke, auth]',
    );
  });

  it('omits the tag block for an empty array', () => {
    expect(formatTestCase(base({ tags: [] }))).toBe('TC-1 · Login works · passed · 1.2s');
  });

  it('appends the owner name, not the email', () => {
    const formatted = formatTestCase(
      base({ tags: ['smoke'], owner: { name: 'Ann Kowalska', email: 'ann@example.com' } }),
    );
    expect(formatted).toBe('TC-1 · Login works · passed · 1.2s [smoke] (Ann Kowalska)');
    expect(formatted).not.toContain('@example.com');
  });

  it('works with an owner but no tags', () => {
    expect(formatTestCase(base({ owner: { name: 'Bo', email: 'bo@x.test' } }))).toBe(
      'TC-1 · Login works · passed · 1.2s (Bo)',
    );
  });

  it('treats id as readonly', () => {
    const testCase = base();
    // @ts-expect-error `id` is readonly once you write the real interface.
    testCase.id = 'TC-999';
    expect(true).toBe(true);
  });
});

describe('3.2 countByStatus', () => {
  it('returns every status even for an empty input', () => {
    expect(countByStatus([])).toEqual({ passed: 0, failed: 0, skipped: 0, flaky: 0 });
  });

  it('counts each status', () => {
    const cases = [
      base({ status: 'passed' }),
      base({ status: 'passed' }),
      base({ status: 'failed' }),
      base({ status: 'flaky' }),
    ];
    expect(countByStatus(cases)).toEqual({ passed: 2, failed: 1, skipped: 0, flaky: 1 });
  });
});

describe('3.3 cloneConfig', () => {
  const config = (): SuiteConfig => ({
    name: 'smoke',
    retries: 2,
    headers: { Accept: 'application/json' },
    tags: ['smoke'],
  });

  it('copies the scalars', () => {
    const original = config();
    const copy = cloneConfig(original);
    expect(copy).toEqual(original);
    expect(copy).not.toBe(original);
  });

  it('does not share the headers object', () => {
    const original = config();
    const copy = cloneConfig(original);
    copy.headers['Authorization'] = 'Bearer secret';
    expect(original.headers).toEqual({ Accept: 'application/json' });
  });

  it('does not share the tags array', () => {
    const original = config();
    const copy = cloneConfig(original);
    copy.tags.push('regression');
    expect(original.tags).toEqual(['smoke']);
  });

  it('survives mutation in the other direction too', () => {
    const original = config();
    const copy = cloneConfig(original);
    original.tags.push('nightly');
    expect(copy.tags).toEqual(['smoke']);
  });
});

describe('3.4 mergeConfig', () => {
  const base3_4 = (): SuiteConfig => ({
    name: 'smoke',
    retries: 2,
    headers: { Accept: 'application/json' },
    tags: ['smoke'],
  });

  it('keeps the base when the override is empty', () => {
    expect(mergeConfig(base3_4(), {})).toEqual(base3_4());
  });

  it('lets an explicit zero through', () => {
    expect(mergeConfig(base3_4(), { retries: 0 }).retries).toBe(0);
  });

  it('merges headers key by key, override wins', () => {
    const merged = mergeConfig(base3_4(), {
      headers: { Accept: 'text/html', Authorization: 'Bearer x' },
    });
    expect(merged.headers).toEqual({ Accept: 'text/html', Authorization: 'Bearer x' });
  });

  it('concatenates tags and removes duplicates, base order first', () => {
    const merged = mergeConfig(base3_4(), { tags: ['auth', 'smoke', 'auth'] });
    expect(merged.tags).toEqual(['smoke', 'auth']);
  });

  it('mutates neither argument', () => {
    const original = base3_4();
    const override = { tags: ['auth'], headers: { Authorization: 'x' } };
    mergeConfig(original, override);
    expect(original).toEqual(base3_4());
    expect(override).toEqual({ tags: ['auth'], headers: { Authorization: 'x' } });
  });

  it('returns a fresh object', () => {
    const original = base3_4();
    expect(mergeConfig(original, {})).not.toBe(original);
  });
});

describe('3.5 createReporter', () => {
  it('defaults `open` to never', () => {
    expect(createReporter({ outputDir: 'reports' })).toBe('reports:never');
  });

  it('uses the supplied mode', () => {
    expect(createReporter({ outputDir: 'reports', open: 'on-failure' })).toBe(
      'reports:on-failure',
    );
  });

  it('rejects a typo in an object literal', () => {
    // @ts-expect-error `opne` is not a property of ReporterOptions.
    expect(createReporter({ outputDir: 'reports', opne: 'always' })).toBe('reports:never');
  });

  it('rejects a value outside the union', () => {
    // @ts-expect-error 'sometimes' is not one of the three allowed modes.
    expect(createReporter({ outputDir: 'reports', open: 'sometimes' })).toBe(
      'reports:sometimes',
    );
  });
});
